apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-pod
  name: nginx-pod
spec:
  nodeSelector:
    hostpath-node: nginx-data       
  volumes:        
  - name: "data"
    hostPath:
      path: "/usr/share/nginx/html"
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: "data"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP

